apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapp
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: testapp
  template:
    metadata:
      labels:
        app: testapp
    spec:
      containers:
        - name: testapp
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          ports:
            - containerPort: 80
{{- with .Values.resources }}
{{ toYaml . | indent 10 }}
{{- end }}
{{- with .Values.securityContext }}
{{ toYaml . | indent 10 }}
{{- end }}
