replicaCount: 1

image:
  repository: nginx
  tag: 1.21
  pullPolicy: IfNotPresent

resources:
  limits:
    memory: 256Mi
    cpu: 500m
  requests:
    memory: 128Mi
    cpu: 250m

securityContext:
  runAsNonRoot: true
  readOnlyRootFilesystem: true
